"use client";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Global/Footer";
import ScrollToTopButton from "@/components/Global/ScrollToTopButton";
import { ThemeProvider } from "@/context/ThemeContext";
import DonateButton from "@/components/Global/DonateButton";
import ContactPopupForm from "@/components/Global/ContactPopupForm";
import { useEffect, useState } from "react";
import { AuthProvider } from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Palmcare",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showPopup, setShowPopup] = useState(false);

  useEffect(() => {
    const handleMouseLeave = (e) => {
      if (e.clientY <= 0) {
        setShowPopup(true);
      }
    };

    document.addEventListener("mouseleave", handleMouseLeave);

    // Cleanup the event listener on component unmount
    return () => {
      document.removeEventListener("mouseleave", handleMouseLeave);
    };
  }, []);

  const closePopup = () => {
    setShowPopup(false);
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider>
            <ScrollToTopButton />
            {showPopup && <ContactPopupForm onClose={closePopup} />}
            <DonateButton />
            {children}
            <Footer />
            <ToastContainer />

          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
